apiVersion: 1

deleteDatasources:
  - name: TimescaleDB Maritime
    orgId: 1

datasources:
  - name: TimescaleDB Maritime
    uid: timescaledb-maritime
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
      maxOpenConns: 20
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: true
    editable: false
